const SEED_DATA = {
  me: {
    name: "Avery Chen",
    headline: "Product Manager · Fintech",
    location: "San Francisco, CA",
    about: "Building products people love at a payments startup. Weekend hiker, amateur espresso barista.",
    skills: ["Product Strategy", "Roadmapping", "SQL", "Data Analysis", "User Research"],
    interests: ["Hiking", "Espresso", "Startups", "Tennis"],
  },
  candidates: [
    {
      id: "p1",
      name: "Jordan Blake",
      headline: "Software Engineer at Google",
      location: "Mountain View, CA",
      age: 29,
      height: "5'11\"",
      skills: ["TypeScript", "Machine Learning", "System Design", "Rust"],
      interests: ["Trail Running", "Chess", "Indie Games"],
      mutual: ["Sofia M.", "Liam T."],
      verified: true,
      pitch: "I debug code and people's day. Looking for someone who ships things and smiles.",
      colors: ["#0a66c2", "#6db3f2"],
      photo: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    {
      id: "p2",
      name: "Priya Nair",
      headline: "Design Lead · Figma alum",
      location: "San Francisco, CA",
      age: 27,
      height: "5'6\"",
      skills: ["Product Design", "Prototyping", "Design Systems", "Branding"],
      interests: ["Ceramics", "Jazz", "Film Photography"],
      mutual: ["Ava R.", "Noah K."],
      verified: true,
      pitch: "I make interfaces and breakfast tacos. Swipe for craft coffee and honest feedback.",
      colors: ["#b0257e", "#e18ac2"],
      photo: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    {
      id: "p3",
      name: "Marcus Reed",
      headline: "Data Scientist at Airbnb",
      location: "Oakland, CA",
      age: 31,
      height: "6'1\"",
      skills: ["Python", "Statistics", "NLP", "A/B Testing"],
      interests: ["Bouldering", "Sourdough", "Science Fiction"],
      mutual: ["Sofia M."],
      verified: false,
      pitch: "I run experiments by day and bake bread by night. 95% confidence in a good first date.",
      colors: ["#157347", "#4cb07f"],
      photo: "https://randomuser.me/api/portraits/men/71.jpg",
    },
    {
      id: "p4",
      name: "Dana Okafor",
      headline: "Founder · opsio.ai",
      location: "San Francisco, CA",
      age: 28,
      height: "5'8\"",
      skills: ["Fundraising", "SaaS", "Golang", "Growth"],
      interests: ["Kite Surfing", "Podcasts", "Pasta Making"],
      mutual: ["Liam T.", "Ava R."],
      verified: true,
      pitch: "Founder of an AI ops startup. Ask me about runway, or let's just talk travel.",
      colors: ["#7a4a1e", "#c98a4b"],
      photo: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    {
      id: "p5",
      name: "Leo Nakamura",
      headline: "Product Designer · Airbnb",
      location: "Berkeley, CA",
      age: 30,
      height: "5'10\"",
      skills: ["UX Research", "Figma", "Motion Design", "Accessibility"],
      interests: ["Bouldering", "Origami", "Indie Films"],
      mutual: ["Noah K.", "Sofia M."],
      verified: false,
      pitch: "I design for delightful moments. Let's find some IRL ones together.",
      colors: ["#0f6f70", "#43b5b6"],
      photo: "https://randomuser.me/api/portraits/men/75.jpg",
    },
    {
      id: "p6",
      name: "Chloe Fontaine",
      headline: "Growth Marketing · TikTok",
      location: "Los Angeles, CA",
      age: 26,
      height: "5'5\"",
      skills: ["Growth Loops", "Content Strategy", "Analytics", "SEO"],
      interests: ["Yoga", "Vinyl Records", "Street Food"],
      mutual: ["Ava R."],
      verified: true,
      pitch: "I make things go viral — but our DMs are end-to-end encrypted, promise.",
      colors: ["#8e24aa", "#c77bdd"],
      photo: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    {
      id: "p7",
      name: "Sam Whitfield",
      headline: "Frontend Engineer · Stripe",
      location: "San Francisco, CA",
      age: 32,
      height: "6'0\"",
      skills: ["React", "GraphQL", "Web Performance", "Open Source"],
      interests: ["Skiing", "Craft Beer", "Board Games"],
      mutual: ["Liam T.", "Noah K.", "Ava R."],
      verified: true,
      pitch: "I ship fast and review PRs with kindness. Hoping to do the same for dinner plans.",
      colors: ["#9a3412", "#e0703c"],
      photo: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    {
      id: "p8",
      name: "Zara Haddad",
      headline: "ML Engineer · OpenAI",
      location: "San Francisco, CA",
      age: 29,
      height: "5'7\"",
      skills: ["PyTorch", "LLMs", "Reinforcement Learning", "Distributed Systems"],
      interests: ["Cycling", "Arabic Poetry", "Climbing"],
      mutual: ["Sofia M.", "Ava R."],
      verified: true,
      pitch: "I align models and misalign with boring dates. Strong opinions, warm heart.",
      colors: ["#3b5bdb", "#7d96f0"],
      photo: "https://randomuser.me/api/portraits/women/79.jpg",
    },
    {
      id: "p9",
      name: "Tomás Rivera",
      headline: "Tech Lead · Netflix",
      location: "San Jose, CA",
      age: 34,
      height: "5'9\"",
      skills: ["Java", "Microservices", "Kubernetes", "Mentoring"],
      interests: ["Salsa", "Road Trips", "Coffee Roasting"],
      mutual: ["Liam T."],
      verified: false,
      pitch: "Leading streaming infra. My grandma thinks I should find a date before my next promotion.",
      colors: ["#862e2e", "#c05b5b"],
      photo: "https://randomuser.me/api/portraits/men/33.jpg",
    },
    {
      id: "p10",
      name: "Imani Brooks",
      headline: "Product Manager · Notion",
      location: "San Francisco, CA",
      age: 28,
      height: "5'9\"",
      skills: ["Product Strategy", "Agile", "Metrics", "Content"],
      interests: ["Marathons", "Poetry Slams", "Vegan Cooking"],
      mutual: ["Noah K.", "Sofia M."],
      verified: true,
      pitch: "I organize chaos for a living. My to-do list is flawless; my dating life is a work in progress.",
      colors: ["#14532d", "#3f9b5f"],
      photo: "https://randomuser.me/api/portraits/women/90.jpg",
    },
    {
      id: "p11",
      name: "Yu Hang Joachim Sin",
      headline: "Year 2 Student @ Brunel · CS (AI)",
      location: "London, UK",
      age: 20,
      height: "5'10\"",
      skills: ["Computer Science", "AI", "Software Development", "Python"],
      interests: ["Gaming", "Tech Meetups", "Football"],
      mutual: ["Melis", "Saba"],
      verified: true,
      featured: true,
      pitch: "Year 2 CS (AI) student at Brunel. Building cool stuff and looking for someone to build plans with.",
      colors: ["#0f5f8f", "#4aa3d6"],
      photo: "photos/joachim.png",
    },
    {
      id: "p12",
      name: "Andrii Kontovskyi",
      headline: "Student @ Brunel · Cybersecurity & AI",
      location: "London, UK",
      age: 22,
      height: "6'0\"",
      skills: ["Cybersecurity", "Artificial Intelligence", "Networking", "Linux"],
      interests: ["Hacking Challenges", "Hiking", "Tech Talks"],
      mutual: ["Yu Hang Joachim", "Saba"],
      verified: true,
      featured: true,
      pitch: "Cybersecurity & AI student at Brunel. Securing systems by day, securing a date by night.",
      colors: ["#6a1b9a", "#b06fd6"],
      photo: "photos/andrii.png",
    },
    {
      id: "p13",
      name: "Faizan Alvi",
      headline: "CS Student @ Brunel · Cybersecurity Intern",
      location: "United Kingdom",
      age: 21,
      height: "5'11\"",
      skills: ["Cybersecurity", "Python", "Networking", "GitHub"],
      interests: ["Traveling", "Photography", "CTF Challenges"],
      mutual: ["Ava R."],
      verified: true,
      featured: true,
      pitch: "CS student at Brunel, cybersecurity intern at xfacilitygroup. 500+ connections and counting — let's add one more.",
      colors: ["#1b7a3d", "#5cb88a"],
      photo: "photos/faizan.png",
    },
  ],
  convos: {
    p1: [
      { from: "them", text: "Hey! Your profile came up twice in my recommendations. Algorithm clearly ships us." },
      { from: "me", text: "The algorithm has excellent taste. What are you building at Google?" },
      { from: "them", text: "Working on ML-powered search features. How about you?" },
    ],
    p2: [
      { from: "me", text: "Saw you're into ceramics. Do you throw on the wheel or hand-build?" },
      { from: "them", text: "Wheel throwing! It's basically design critique but with clay. What about you?" },
    ],
  },
  pendingLikes: ["p4"],
};
